TYPE "typeArticleDefinition"
VERSION : 0.1
   STRUCT
      nProgrNumber : DINT;   // 0 = free/unused; 9999 = wrong article
      nXbreiteRechts : DINT;
      nXbreitelinks : DINT;
      nYlaenge : DINT;
      nTolX : DINT;            // optionale Toleranz X für diesen Artikel (abs)
      nTolY : DINT;            // optionale Toleranz Y für diesen Artikel (abs)
      nRelTolX : DINT;         // optionale relative Toleranz X in Prozent (0=unused)
      nRelTolY : DINT;         // optionale relative Toleranz Y in Prozent (0=unused)
   END_STRUCT;
END_TYPE

TYPE "typeCarriageData"
VERSION : 0.1
   STRUCT
      nLaufWgNrNumber : DINT; 
      nProgrNumber : DINT; // 0 = free/unused; 9999 = wrong article
      nXbreiteRechts : DINT;
      nXbreitelinks : DINT;
      nYlaenge       : DINT;
      nTolX          : DINT; // optionale Toleranz X für diesen Artikel (abs)
      nTolY          : DINT; // optionale Toleranz Y für diesen Artikel (abs)
      nRelTolX       : DINT; // optionale relative Toleranz X in Prozent (0=unused)
      nRelTolY       : DINT; // optionale relative Toleranz Y in Prozent (0=unused)
      bIsNewArticle  : BOOL;
      bDataValid     : BOOL;
      nActXbreiteRechts : DINT;
      nActXbreitelinks : DINT;
      nActYlaenge       : DINT;
   END_STRUCT;
END_TYPE
